Document: honeyd
Title: Debian honeyd Manual
Author: <insert document author here>
Abstract: This manual describes what honeyd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/honeyd/honeyd.sgml.gz

Format: postscript
Files: /usr/share/doc/honeyd/honeyd.ps.gz

Format: text
Files: /usr/share/doc/honeyd/honeyd.text.gz

Format: HTML
Index: /usr/share/doc/honeyd/html/index.html
Files: /usr/share/doc/honeyd/html/*.html
